apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-sample-ingress
  namespace: test-sample
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

    # üö´ Cache disable
    nginx.ingress.kubernetes.io/proxy-no-cache: "1"
    nginx.ingress.kubernetes.io/proxy-cache-bypass: "1"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header Cache-Control "no-store, no-cache, max-age=0, must-revalidate" always;
      add_header Pragma "no-cache" always;
      add_header Expires "0" always;
spec:
  tls:
  - hosts:
    - sumit.sujeetkushwaha.shop
    secretName: test-sample-tls
  rules:
  - host: sumit.sujeetkushwaha.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sumit-welcome-svc   # ‚ö†Ô∏è apne service name se match kare
            port:
              number: 80
