apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/auth-type: basic
    #nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
    #nginx.ingress.kubernetes.io/auth-realm: Authentication Required
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx  # Nginx Ingress Controller pick karega
  tls:
    - hosts:
        - prometheus.sujeetkushwaha.shop
      secretName: prometheus-tls  # Cert-manager ke dwara generate TLS secret
  rules:
    - host: prometheus.sujeetkushwaha.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
