apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx   # NGINX ingress controller specify kar rahe hain
  rules:
  - host: prometheus.sujeetkushwaha.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-operated  # Prometheus service ka naam
            port:
              number: 9090  # Prometheus ka default port
  tls:
  - hosts:
    - prometheus.sujeetkushwaha.shop
    secretName: prometheus-tls  # Prometheus ka TLS certificate secret
