apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: chess-game
spec:
  acme:
    email: sujeetkushwaha14@gmail.com   # ðŸ‘ˆ apna email daalo
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - http01:
          ingress:
            class: nginx   # ðŸ‘ˆ agar nginx ingress hai
