apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chess-tls
  namespace: chess-game
spec:
  secretName: chess-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - chess.sujeetkushwaha.shop
