apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chess-game-tls
  namespace: chess-game
spec:
  secretName: chess-game-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - chess.sujeetkushwaha.shop
