apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chess-game-tls-1
  namespace: chess
spec:
  secretName: chess-game-tls-1
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - chess.sujeetkushwaha.shop
