apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chess-tls
  namespace: chess-game
spec:
  secretName: chess-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  commonName: chess.sujeetkushwaha.shop
  dnsNames:
    - chess.sujeetkushwaha.shop
  privateKey:
    algorithm: RSA
    size: 2048
