apiVersion: v1
kind: Service
metadata:
  name: chess-game-service
  namespace: chess-game  # Set the namespace to 'chess'
spec:
  selector:
    app: chess-game
  ports:
    - protocol: TCP
      port: 80       # External port for HTTP
      targetPort: 8000  # Internal container port
  type: ClusterIP
